# Generated by Django 5.2.10 on 2026-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    GOAL: Add indexes to optimize common queries.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - All indexes are reversible
      - Migration can be safely rolled back
    """

    dependencies = [
        ("feature_flags", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(
                fields=["is_secret", "created_at"],
                name="system_settings_sec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["enabled", "created_at"],
                name="feature_flags_en_idx",
            ),
        ),
    ]
