# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='feature_fla_enabled_418110_idx',
            old_name='feature_flags_en_idx',
        ),
        migrations.RenameIndex(
            model_name='systemsetting',
            new_name='system_sett_is_secr_828685_idx',
            old_name='system_settings_sec_idx',
        ),
    ]
