# Generated by Django 5.2.10 on 2026-01-30 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0003_rename_feature_flags_en_idx_feature_fla_enabled_418110_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemsetting",
            old_name="system_sett_is_secr_828685_idx",
            new_name="sysset_is_secret_created_at",
        ),
        migrations.RenameIndex(
            model_name="featureflag",
            old_name="feature_fla_enabled_418110_idx",
            new_name="ff_enabled_created_at",
        ),
    ]
