# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_user_id_037132_idx',
            old_name='sub_user_active_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_access__d39209_idx',
            old_name='sub_access_token_idx',
        ),
    ]
