# Generated by Django 5.2.10 on 2026-01-30

from django.db import migrations, models


"""
GOAL: Convert blank Subscription.access_token values to NULL to avoid unique constraint conflicts.

PARAMETERS:
  apps: Any - Migration app registry - Provided by Django
  schema_editor: Any - DB schema editor - Provided by Django

RETURNS:
  None

RAISES:
  None

GUARANTEES:
  - All rows with access_token='' are updated to access_token=NULL
"""
def _set_empty_access_token_to_null(apps, schema_editor) -> None:
    Subscription = apps.get_model("subscriptions", "Subscription")
    Subscription.objects.filter(access_token="").update(access_token=None)


class Migration(migrations.Migration):
    """
    GOAL: Allow NULL access_token so multiple inactive subscriptions can exist without generating tokens.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - access_token becomes nullable at DB level
      - Existing empty-string tokens are migrated to NULL
    """

    dependencies = [
        ("subscriptions", "0003_rename_sub_user_active_expires_idx_subscriptio_user_id_037132_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="access_token",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.RunPython(_set_empty_access_token_to_null, reverse_code=migrations.RunPython.noop),
    ]

