# Generated by Django 5.2.10 on 2026-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    GOAL: Add additional indexes to optimize common queries.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - All indexes are reversible
      - Migration can be safely rolled back
    """

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"],
                name="payments_status_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["payment", "created_at"],
                name="payment_hist_pay_cr_idx",
            ),
        ),
    ]
