# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_additional_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_426d4f_idx',
            old_name='payments_status_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='payment_his_payment_8ce054_idx',
            old_name='payment_hist_pay_cr_idx',
        ),
    ]
