# Generated by Django 5.2.10 on 2026-01-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_payments_status_cr_idx_payments_status_426d4f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_yukassa_b1bc9f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_user_created_at_idx',
            old_name='payments_user_id_03af7e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_created_at_idx',
            old_name='payments_status_426d4f_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='payhist_event_type_created_at',
            old_name='payment_his_event_t_45050d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='payhist_payment_created_at',
            old_name='payment_his_payment_8ce054_idx',
        ),
    ]
