# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driverprofile',
            name='auth_driver_telegram_id_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramsession',
            new_name='telegram_se_user_id_dc9a64_idx',
            old_name='auth_telegram_user_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramsession',
            new_name='telegram_se_expires_48318b_idx',
            old_name='auth_telegram_expires_idx',
        ),
    ]
