# Generated by Django 5.2.10 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver_auth", "0003_remove_driverprofile_auth_driver_telegram_id_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

