# Generated by Django 5.2.10 on 2026-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    GOAL: Add additional indexes to optimize common queries.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - All indexes are reversible
      - Migration can be safely rolled back
    """

    dependencies = [
        ("promocodes", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["disabled", "valid_until"],
                name="promo_codes_dis_v_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocodeusage",
            index=models.Index(
                fields=["success", "used_at"],
                name="promo_code_use_suc_idx",
            ),
        ),
    ]
