# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_add_additional_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promocode',
            new_name='promo_codes_disable_c8082e_idx',
            old_name='promo_codes_dis_v_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='promo_code__success_33f001_idx',
            old_name='promo_code_use_suc_idx',
        ),
    ]
