# Generated by Django 5.2.10 on 2026-01-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_rename_promo_codes_dis_v_idx_promo_codes_disable_c8082e_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promocode',
            new_name='pc_action_valid_until',
            old_name='promo_codes_action_e65d40_idx',
        ),
        migrations.RenameIndex(
            model_name='promocode',
            new_name='pc_disabled_valid_until',
            old_name='promo_codes_disable_c8082e_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='pcu_promo_code_used_at',
            old_name='promo_code__promo_c_300e33_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='pcu_user_used_at',
            old_name='promo_code__user_id_657efc_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='pcu_success_used_at',
            old_name='promo_code__success_33f001_idx',
        ),
    ]
