# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_3684e9_idx',
            old_name='audit_user_action_created_idx',
        ),
    ]
