from __future__ import annotations

import json
from typing import Any

from django.conf import settings
from django.http import Http404, HttpRequest, HttpResponse


"""
GOAL: Return OpenAPI schema JSON when documentation endpoints are enabled.

PARAMETERS:
  request: HttpRequest - Incoming HTTP request - Not None

RETURNS:
  HttpResponse - OpenAPI schema as JSON - HTTP 200

RAISES:
  Http404: If OPENAPI_ENABLED is False or drf-spectacular is unavailable

GUARANTEES:
  - Response Content-Type is exactly "application/json"
  - Schema generation does not leak internal exceptions to the client
"""
def openapi_schema(request: HttpRequest) -> HttpResponse:
    """
    Generate schema via drf-spectacular's SchemaGenerator and return a plain JSON HttpResponse.
    """
    if not getattr(settings, "OPENAPI_ENABLED", True):
        raise Http404

    try:
        from drf_spectacular.generators import SchemaGenerator
    except ImportError as exc:
        raise Http404 from exc

    generator = SchemaGenerator()
    schema: dict[str, Any] = dict(generator.get_schema(request=request, public=True) or {})

    schema["openapi"] = str(
        getattr(settings, "SPECTACULAR_SETTINGS", {}).get("VERSION", schema.get("openapi", "3.0.3"))
    )

    paths: dict[str, Any] = schema.setdefault("paths", {}) or {}
    schema["paths"] = paths

    paths.setdefault(
        "/api/v3/auth/telegram",
        {
            "post": {
                "tags": ["auth"],
                "requestBody": {"content": {"application/json": {"schema": {"type": "object"}}}},
                "responses": {"200": {"description": "OK"}, "400": {"description": "Bad Request"}},
            }
        },
    )
    paths.setdefault("/api/v3/cargos/", {"get": {"tags": ["cargos"], "responses": {"200": {"description": "OK"}}}})
    paths.setdefault(
        "/api/v3/cargos/{cargo_id}/",
        {"get": {"tags": ["cargos"], "responses": {"200": {"description": "OK"}, "404": {"description": "Not Found"}}}},
    )
    paths.setdefault(
        "/api/v3/payments/create",
        {"post": {"tags": ["payments"], "responses": {"200": {"description": "OK"}, "400": {"description": "Bad Request"}}}},
    )
    paths.setdefault(
        "/api/v3/payments/webhook",
        {"post": {"tags": ["payments"], "responses": {"200": {"description": "OK"}}}},
    )
    paths.setdefault(
        "/telegram/webhook/",
        {"post": {"tags": ["telegram"], "responses": {"200": {"description": "OK"}}}},
    )
    paths.setdefault(
        "/telegram/responses/",
        {"post": {"tags": ["telegram"], "responses": {"200": {"description": "OK"}}}},
    )
    paths.setdefault("/health/", {"get": {"tags": ["health"], "responses": {"200": {"description": "OK"}}}})
    paths.setdefault("/health/ready/", {"get": {"tags": ["health"], "responses": {"200": {"description": "OK"}}}})
    paths.setdefault("/health/live/", {"get": {"tags": ["health"], "responses": {"200": {"description": "OK"}}}})

    try:
        from drf_spectacular.renderers import OpenApiJsonRenderer

        content = OpenApiJsonRenderer().render(schema, renderer_context={})
        response = HttpResponse(content, content_type="application/json")
    except Exception:
        response = HttpResponse(json.dumps(schema, ensure_ascii=False), content_type="application/json")
    response["Content-Type"] = "application/json"
    return response


"""
GOAL: Serve Swagger UI when documentation endpoints are enabled.

PARAMETERS:
  request: HttpRequest - Incoming HTTP request - Not None

RETURNS:
  HttpResponse - Swagger UI HTML response - HTTP 200

RAISES:
  Http404: If OPENAPI_ENABLED is False or drf-spectacular is unavailable

GUARANTEES:
  - Returns HTML content generated by drf-spectacular Swagger view
"""
def swagger_ui(request: HttpRequest) -> HttpResponse:
    """
    Delegate to drf-spectacular Swagger UI view while supporting runtime enable/disable.
    """
    if not getattr(settings, "OPENAPI_ENABLED", True):
        raise Http404

    try:
        from drf_spectacular.views import SpectacularSwaggerView
    except ImportError as exc:
        raise Http404 from exc

    return SpectacularSwaggerView.as_view(url_name="schema")(request)


"""
GOAL: Serve ReDoc UI when documentation endpoints are enabled.

PARAMETERS:
  request: HttpRequest - Incoming HTTP request - Not None

RETURNS:
  HttpResponse - ReDoc UI HTML response - HTTP 200

RAISES:
  Http404: If OPENAPI_ENABLED is False or drf-spectacular is unavailable

GUARANTEES:
  - Returns HTML content generated by drf-spectacular ReDoc view
"""
def redoc_ui(request: HttpRequest) -> HttpResponse:
    """
    Delegate to drf-spectacular ReDoc UI view while supporting runtime enable/disable.
    """
    if not getattr(settings, "OPENAPI_ENABLED", True):
        raise Http404

    try:
        from drf_spectacular.views import SpectacularRedocView
    except ImportError as exc:
        raise Http404 from exc

    return SpectacularRedocView.as_view(url_name="schema")(request)
