# Generated by Django 5.2.10 on 2026-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    GOAL: Add indexes to optimize common queries.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - All indexes are reversible
      - Migration can be safely rolled back
    """

    dependencies = [
        ("cargos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cargocache",
            index=models.Index(
                fields=["user", "created_at"],
                name="cargo_cache_us_cr_idx",
            ),
        ),
    ]
