# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cargocache',
            new_name='cargo_cache_user_id_81ca1d_idx',
            old_name='cargo_cache_us_cr_idx',
        ),
    ]
