# Generated by Django 5.2.10 on 2026-01-30

from django.db import migrations


class Migration(migrations.Migration):
    """
    GOAL: Rename CargoCache composite indexes to stable, descriptive names.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - Indexes remain functionally identical (only names change)
      - Migration is reversible via Django migration framework
    """

    dependencies = [
        ("cargos", "0003_rename_cargo_cache_us_cr_idx_cargo_cache_user_id_81ca1d_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cargocache",
            old_name="cargo_cache_user_id_67d046_idx",
            new_name="cargo_cache_user_cache_key_idx",
        ),
        migrations.RenameIndex(
            model_name="cargocache",
            old_name="cargo_cache_user_id_81ca1d_idx",
            new_name="cargo_cache_user_created_at",
        ),
    ]
