# Generated by Django 5.2.10 on 2026-01-08 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCargoResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo_id', models.CharField(db_index=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_cargo_responses',
                'indexes': [models.Index(fields=['cargo_id', 'created_at'], name='driver_carg_cargo_i_a2441c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'cargo_id'), name='uniq_driver_cargo_response')],
            },
        ),
    ]
