# Generated by Django 5.2.10 on 2026-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    GOAL: Add additional indexes to optimize common queries.

    PARAMETERS:
      None

    RETURNS:
      None

    RAISES:
      None

    GUARANTEES:
      - All indexes are reversible
      - Migration can be safely rolled back
    """

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="drivercargoresponse",
            index=models.Index(
                fields=["user", "created_at"],
                name="driver_cargo_us_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drivercargoresponse",
            index=models.Index(
                fields=["status", "created_at"],
                name="driver_cargo_st_cr_idx",
            ),
        ),
    ]
