# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_add_additional_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drivercargoresponse',
            new_name='driver_carg_user_id_6543fc_idx',
            old_name='driver_cargo_us_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='drivercargoresponse',
            new_name='driver_carg_status_6c32af_idx',
            old_name='driver_cargo_st_cr_idx',
        ),
    ]
