# Generated by Django 5.2.10 on 2026-01-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_rename_driver_cargo_us_cr_idx_driver_carg_user_id_6543fc_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drivercargoresponse',
            new_name='dcr_cargo_id_created_at',
            old_name='driver_carg_cargo_i_a2441c_idx',
        ),
        migrations.RenameIndex(
            model_name='drivercargoresponse',
            new_name='dcr_user_created_at',
            old_name='driver_carg_user_id_6543fc_idx',
        ),
        migrations.RenameIndex(
            model_name='drivercargoresponse',
            new_name='dcr_status_created_at',
            old_name='driver_carg_status_6c32af_idx',
        ),
    ]
